# Perfil dev
spring.datasource.url=jdbc:postgresql://localhost:5432/imobfiscal
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.br.fatec.imobfiscal=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
