# Perfil prod
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
logging.level.br.fatec.imobfiscal=INFO
app.cors.allowed-origins=${CORS_ORIGINS}
