# Perfil dev
spring.datasource.url=jdbc:mysql://localhost:3306/imobfiscal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=root
logging.level.br.fatec.imobfiscal=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
